source("LoadData.R")

dataset <- LoadData()
png("plot4.png", width=400, height=400)
par(mfrow=c(2,2))
plot(dataset$Time, dataset$Global_active_power, type="l",  xlab="",  ylab="Global Active Power")
plot(dataset$Time, dataset$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(dataset$Time, dataset$Sub_metering_1, type="l", col="black", xlab="", ylab="Energy sub metering")
lines(dataset$Time, dataset$Sub_metering_2, col="red")
lines(dataset$Time, dataset$Sub_metering_3, col="blue")
legend("topright", col=c("black", "red", "blue"),c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1,box.lwd=0)
plot(dataset$Time, dataset$Global_reactive_power, type="n", xlab="datetime", ylab="Global_reactive_power")
lines(dataset$Time, dataset$Global_reactive_power)
dev.off()
